### ISSUE TITLE
Add command to write a log file of what the current parameters are to a given directory

### ISSUE THREAD

**Issue by raacampbell** [Zapit-Optostim/zapit#61]
Request from @LohseNeuro 
Each experiment will require a log file so we know how it was generated. The log file should contain at least the following:

* stim locations
* laser power
* laser frequency
* ramp down time in ms
* version of Zapit
* version of MATLAB 

So we want a command along the lines of : `hZP.writeExperimentLogFile(dirToWriteTo)`  and have that produce a YAML file with the above information. Can call that at the start of each experiment.

**Comment by raacampbell** [comment]
Done here: 7f8279d2ed9605030f19e933baecfebb233d7b2c
Produces files with contents of this sort:
```
zapitVersion: Zapit version 0.7.0-alpha  --  2023/1/16
MATLAB: MATLAB (R2022b) version 9.13
hostname: Robs-MBP.lan
laserPowerInMW: 5.0
stimFreqInHz: 40.0
offRampDownDuration_ms: 250.0
stimLocations01:
  ML: [3.56, -3.56]
  AP: [-1.24, -1.24]
stimLocations02:
  ML: [3.95, -3.95]
  AP: [-0.08, -0.08]
stimLocations03: {ML: 0.01, AP: -0.91}
stimLocations04:
  ML: [2.73, 1.88]
  AP: [1.66, 0.94]
stimLocations05:
  ML: [-2.73, -2.73]
  AP: [-2.98, -4.09]
```
